### ISSUE TITLE
Wont run in Revit 2017 & Dynamo 1.x

### ISSUE THREAD

**Issue by Casols** [andydandy74/DynamoAutomation#13] opened 2016-09-20 13:30 UTC
Can't get the new update "DynamoAutomation 1.0.0" to work with Dynamo 1.1

It seems that the journal file that is created specifies to use "Dynamo 1.0" in from the "Add-ins" "Visual Programming" ribbon.

Is there any way that i can edit the "Journal.byWorkspacePath" node to run "Dynamo 1.1" instead of "Dynamo 1.0" ?

**Comment by andydandy74** [comment] 2016-09-21 05:54
@Casols - Thanks for reporting. I hadn't tested on Dynamo 1.1.0 yet. While you are right that DynamoAutomation won't run under Dynamo 1.1.0 the underlying issue is likely something else, since the Dynamo addin is registered in the ribbon under the same name for Dynamo 1.0.0 and 1.1.0 (which is why I hadn't bothered testing for 1.1.0 in the first place...).

@ikeough - These are my findings:
- The journal shows that the DynamoAddin is launched successfully. 
- The DynamoRevit log shows that the script was not loaded (or at least it shows that the custom nodes in that script were not loaded which is an indicator for the script not having loaded). 

My suspicion is that between Dynamo 1.0.0 and Dynamo 1.1.1 some changes were made that prevent the Dynamo 1.1.1 addin from reading the ```APIStringStringMapJournalData``` from the journal file that contains ```dynPath```, ```dynShowUI``` and ```dynAutomation``` variables. Maybe a little too much cleanup on your end?

CC @kronz

**Comment by andydandy74** [comment] 2016-09-29 09:39
@Casols - I'll keep this issue open until it is resolved. Today's update only works for Revit 2016, not 2017.

**Comment by MarkThorley** [comment] 2017-04-06 13:05
@andydandy74 any news on Revit 2017 compatibility? Runs into interactive mode as previously discussed, exactly the same setup as 2016, no whitespace and no opening message in Revit, which had previously caused this issue in 2016.

**Comment by andydandy74** [comment] 2017-04-06 13:32
@MarkThorley Sorry, no. I've been meaning to get the Dynamo devs involved in this since my working theory is that this is caused by changes in the Dynamo codebase for Revit 2017 (see above) but was too busy with other stuff so far. Perhaps something was altered to accomodate Dynamo Player? 
@mjkkirschner Who on team Dynamo would know about that?

**Comment by kronz** [comment] 2017-04-06 22:37
@aparajit-pratap @sharadkjaiswal you have any ideas about what might have changed between 1.0 and 1.1 to affect journal playback?

**Comment by ikeough** [comment] 2017-04-06 22:38
@andydandy74 @MarkThorley  Can we intercept one of the journal files that is written to see whether it's ok? If the journal file is OK, then Andrea's theory is more probable. Can we also get a journal file from a Revit run where the execution via journal doesn't work?

**Comment by andydandy74** [comment] 2017-06-07 14:46
@ikeough - These are sample journal files, generated by Dynamo Sandbox and Revit respectively, using sample A1 available on this repo.
* [DynamoGeneratedJournalFile.txt](https://github.com/andydandy74/DynamoAutomation/files/1058331/DynamoGeneratedJournalFile.txt)
* [RevitGeneratedJournalFile.txt](https://github.com/andydandy74/DynamoAutomation/files/1058334/RevitGeneratedJournalFile.txt)

Looking at DynamoRevit.cs, there are huge differences between the 2016 and 2017 branches. I am pretty sure that this is the cause for all this. I noticed there are a lot more journal keys available in the 2017 branch and played around with various combinations of them in the journal file. Unfortunately without success, but I may not have tested all possible permutations of keys and values.
Short summary:
* The journal will get Revit to launch Dynamo
* Slave graphs set to Manual mode will load but not execute
* Slave graphs set to Automatic mode *will* execute but in a lot of cases that would create perpetual loops, so not a good idea to go there

**Comment by andydandy74** [comment] 2017-08-11 07:06
This issue should be fixed with the next release of DynamoAutomation.

**Closed by andydandy74** 2017-08-11 07:06 UTC
Labels: bug
